require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - '.bundle/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rspec/MultipleMemoizedHelpers:
  Enabled: false